### PR TITLE
Added new Rule 12.8 about requesting financial support for Projects

### PR DESCRIPTION
**Pull request by 6a6d74**
plus amendments elsewhere to provide context

### CODE REVIEW

**Comment by 6a6d74** [comment]
Note: I can no longer find the statement of delegated authority for the Managing Directors; I'm sure it used to specify EUR10K? … Presumably if it’s in budget, just need the due diligence and dual signatories as according to the financial rule supplement?

**Comment by 6a6d74** [comment]
This Rule change is made in accordance with RESOLUTION-BM-2017-02 Vote: 5-0 - in favour - Internal Rule change on funding projects).

**Comment by 6a6d74** [comment]
Closes #228

**Comment by rogers492** [comment]
3. [Action-BM-2017-04 Internal Rule change on funding projects](https://github.com/OpenWIS/openwis-documentation/issues/228)
        1. JT - I have incorporated the rule change as discussed at the meeting in March. Please see [Added new Rule 12.8 about requesting financial support for Projects](https://github.com/OpenWIS/openwis-documentation/pull/279/files)
        2. MDA - PB added a caveat in his email:
        >    • 5.3 Internal rules on funding projects
        >        o MFI agrees with the principle of funding pilot projects if limited to 10k€ or so individually

        3. MDA - I think that PB caveat must be to do with Remy's proposal.
        4. JT - I agree: the Rule change requires funding approval by the Board, so imposing an arbitrary limit doesn't make sense. Unless PB is suggesting the Managing Directors can agree up to €10k. I tried to find in the Rules a statement about delegated authority of €10k fot Managing Directors. Do you remember us discussing that?
        5. MDA - I do not recall that.
        6. JT - Ok. Anyway, getting Board approval can just be an email.
        7. MDA - Yes, that is correct.
        8. JT - I propose that we do not have a €10k limit.
        9. MDA - I agree with that, it was not my intention to limit to €10k; we may choose to limit some at the time. PB mentions _pilot projects_, so he must have been thinking about WIS 2 projects. I will double check with him tomorrow, but we can vote on it today.
        10. JT - Of course, PB could introduce a €10k limit Rule change if he really wanted to.
        11. MDA - Yes. The Rule you are mentioning is for full projects too, not just pilot projects. Ok, let's vote.
        12. RES-OWIS-BM-2017-11: Vote: 4-0 in favour, MFI abstained – Rule change in pull request #279 is approved. OWIS-RES
        13. JT - Does a vote on a Rule change have to be a unanimous decision? I'm looking through the articles... Rule 13 says that Rules may be changed by decision of the Board - with 4 delegates I assume we are quorate.
        14. WQ - Do we have a default?
        15. JT - Unless it specifically says it must be unanimous then a majority is ok.
        16. JT - Did you say it has to be unanimous?
        17. JT - No, some decisions must be unanimous, for example membership of the Board, but in this case it just says: by decision of the Board.
        18. MDA - We should have that in the articles somewhere.
        19. WQ - Yes, Article 12.11:
        > Except where these Articles of Association expressly require any matter to be decided unanimously, or by a simple majority, motions raised at a Board Meeting shall be carried by a three-quarters majority

        20. JT - So 4/5 > 3/4: resolution carried.
        21. JT - So PR [Action-BM-2017-07 Merge PR#279 New Rule 12.8](https://github.com/OpenWIS/openwis-documentation/issues/289) into the website and include Board discussion on PB comments in the pull request comments.

**Comment by rogers492** [comment]
Close #228 Close #289

**Pull request merged**
