### PR TITLE
Publish Dec 2020 SC minutes from gh pages to master

### PR DESCRIPTION
**Pull request by jude2018**

### CODE REVIEW

**Comment by solson-nws** [comment]
@jude2018 :  It appears there are conflicts to resolve first:

 Conflicting files
_minutes/.DS_Store
_minutes/board/2020-10-01-OpenWIS-Board-Meeting-2020-Oct.md

Let me know when this is resolved.

Steve

**Comment by jude2018** [comment]
Not sure what I need to do (remove the conflicting files?)

**Comment by solson-nws** [comment]
Jude:

I think you need to sync the two files between the version in the master
branch and the version on gh-pages.  I believe this is where the
discrepancy is.

HTHs

Steve

**Comment by jude2018** [comment]
Hi Steve,

I don’t know how to do this.  So will need some help from yourself of Yves.  Perhaps, via short MS Teams session?

Jude

**Comment by solson-nws** [comment]
Yves and Jude:

What day(s) work best for you, and then what specific times on those days
work?

Steve

**Comment by jude2018** [comment]
Great

For me – 10th or 12th 1600 to 1630 UK time

**Comment by solson-nws** [comment]
Ok.  What about you Yves?

Steve

**Comment by solson-nws** [comment]
Hello, 

I am not available the 10th, 11th and never on friday afternoon. 
I would prefer the 8th, 9th or the 15,16,17,18 of February. 

Could you describe more precisely the problem pls? 
Does it happen when you're making a git pull ? 


Cheers, 

Yves. 

----- Météo-France ----- 
Yves GOUPIL 
DSI/DEV/WS 
yves.goupil@meteo.fr 
Phone : +33 561078155 


De: "Steve Olson" <steve.r.olson@noaa.gov> 
À: "OpenWIS/openwis-documentation" <reply@reply.github.com>, "GOUPIL Yves" <yves.goupil@meteo.fr>, "Anthonisz, Jude" <jude.anthonisz@metoffice.gov.uk> 
Cc: "OpenWIS/openwis-documentation" <openwis-documentation@noreply.github.com>, "Review requested" <review_requested@noreply.github.com> 
Envoyé: Vendredi 5 Février 2021 14:26:08 
Objet: Re: [OpenWIS/openwis-documentation] Publish Dec 2020 SC minutes from gh pages to master (#618) 

Ok. What about you Yves? 
Steve 

On Fri, Feb 5, 2021 at 3:47 AM jude2018 < [ mailto:notifications@github.com | notifications@github.com ] > wrote: 




Great 

For me – 10th or 12th 1600 to 1630 UK time

**Comment by solson-nws** [comment]
Hi both,

I can be available (1600 to 1630 UK time) on 15,16,17,18 of February.

The problem from my perspective is that I cannot publish the minutes of the SC meeting (or other meetings) on the OpenWIS website.

I am uploading a markup document to gh=pages from Github Desktop and then needed to create a Pull Request (#618) which needs a reviewer (so I assigned Steve as a reviewer).  I think Steve accepted the Pull Request but there are still issues that means that the minutes are not published on the OpenWIS web site.

There is more info in the email thread below

Hope this helps


Best regards

Jude

Jude Anthonisz  Senior Project Manager
Met Office FitzRoy Road Exeter Devon EX1 3PB United Kingdom
Tel: +44 (0)3301351342  or  +44 (0)7824 414579
Email: jude.anthonisz@metoffice.gov.uk<mailto:jude.anthonisz@metoffice.gov.uk> Website: www.metoffice.gov.uk<http://www.metoffice.gov.uk/>

**Comment by solson-nws** [comment]
Hi Jude, 

Ok for the next week. 
I have a question. Did you do all the operations in Github interface or locally after cloning the openwis-documentation project, via git command lines, on your PC? 

After cloning the openwis-documentation github project locally, I reproduced with git command line the auto-merging (fusion) conflict: 

[openwis@linux openwis-documentation]$ git clone https://github.com/OpenWIS/openwis-documentation.git 
[openwis@linux openwis-documentation]$ git checkout master 
Switched to branch 'master' 
[openwis@linux openwis-documentation]$ git merge gh-pages 
warning: Cannot merge binary files: _minutes/.DS_Store (HEAD vs. gh-pages) 
Auto-merging _minutes/board/2020-10-01-OpenWIS-Board-Meeting-2020-Oct.md 
CONFLICT (add/add): Merge conflict in _minutes/board/2020-10-01-OpenWIS-Board-Meeting-2020-Oct.md 
Auto-merging _minutes/board/2020-06-04and05-OpenWIS-Board-Meeting-2020-May.md 
Auto-merging _minutes/board/2019-05-23-OpenWIS-Board-Meeting-2019-May.md 
Auto-merging _minutes/.DS_Store 
CONFLICT (content): Merge conflict in _minutes/.DS_Store 
Automatic merge failed; fix conflicts and then commit the result. 

The file " in _minutes/board/2020-10-01-OpenWIS-Board-Meeting-2020-Oct.md" seems easy to correct but I don't know what is the binary file ".DS_Store" for. Is this file created by Github? 

Cheers, 

Yves. 

----- Météo-France ----- 
Yves GOUPIL 
DSI/DEV/WS 
yves.goupil@meteo.fr 
Phone : +33 561078155 


De: "Anthonisz, Jude" <jude.anthonisz@metoffice.gov.uk> 
À: "GOUPIL Yves" <yves.goupil@meteo.fr>, "Steve Olson" <steve.r.olson@noaa.gov> 
Cc: "OpenWIS/openwis-documentation" <reply@reply.github.com> 
Envoyé: Lundi 8 Février 2021 11:09:28 
Objet: RE: [OpenWIS/openwis-documentation] Publish Dec 2020 SC minutes from gh pages to master (#618) 



Hi both, 



I can be available (1600 to 1630 UK time) on 15,16,17,18 of February. 



The problem from my perspective is that I cannot publish the minutes of the SC meeting (or other meetings) on the OpenWIS website. 



I am uploading a markup document to gh=pages from Github Desktop and then needed to create a Pull Request (#618) which needs a reviewer (so I assigned Steve as a reviewer). I think Steve accepted the Pull Request but there are still issues that means that the minutes are not published on the OpenWIS web site. 



There is more info in the email thread below 



Hope this helps 





Best regards 



Jude 



Jude Anthonisz Senior Project Manager 

Met Office FitzRoy Road Exeter Devon EX1 3PB United Kingdom 
Tel: +44 (0)3301351342 or +44 (0)7824 414579 
Email: [ mailto:jude.anthonisz@metoffice.gov.uk | jude.anthonisz@metoffice.gov.uk ] Website: [ http://www.metoffice.gov.uk/ | www.metoffice.gov.uk ]

**Comment by solson-nws** [comment]
HI Yves,

Great.  Ill schedule a meeting when Steve confirms his availability.

I created the markup text file in Atom and uploaded it from Github Desktop (both are on my Mac computer).  I have done this several times before and everything worked OK (the most recent previous update was in September 2020)

DS store – could be file/index from the mac ? (Its not a file that created or want updating)

Hope this helps

Jude

**Comment by solson-nws** [comment]
Let's go with the 16th if that works

steve

**Comment by solson-nws** [comment]
16th is a date (not 14th 😊)

Jude

**Comment by solson-nws** [comment]
will you send out teams invite?

Steve

**Comment by jude2018** [comment]
done

**Review by solson-nws — APPROVED** [review]

**Pull request closed without merging**
